version: "2"
run:
  timeout: 10m
  modules-download-mode: vendor
linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - whitespace
  settings:
    misspell:
      ignore-rules:
        - creater
    staticcheck:
      checks:
        - all
        # Using a deprecated function, variable, constant or field.
        # https://staticcheck.dev/docs/checks/#SA1019
        - -SA1019
        # Poorly chosen identifier.
        # https://staticcheck.dev/docs/checks/#ST1003
        - -ST1003
        # Incorrectly formatted error string.
        # https://staticcheck.dev/docs/checks/#ST1005
        - -ST1005
        # Omit embedded fields from selector expression.
        # https://staticcheck.dev/docs/checks/#QF1008
        - -QF1008
        # Apply De Morgan's law.
        # https://staticcheck.dev/docs/checks/#QF1001
        - -QF1001
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: pkg/storage/memorystorage/v2/
        linters:
          - unused # memory v2 is in alpha and tolerates unused functions or fields
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/clusterpedia-io)
    goimports:
      local-prefixes:
        - github.com/clusterpedia-io
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
