run:
  timeout: 10m
  modules-download-mode: vendor
linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dupl
    - errcheck
    - gci
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - whitespace
linters-settings:
  goimports:
    local-prefixes: github.com/clusterpedia-io
  misspell:
    ignore-words:
      - creater
  gci:
    sections:
      - Standard
      - Default
      - Prefix(github.com/clusterpedia-io)
  staticcheck:
    checks:
      - all
      - "-SA1019" # disable the rule SA1019(Using a deprecated function, variable, constant or field)
output:
  sort-results: true
