---
apiVersion: batch/v1
kind: Job
metadata:
  name: check-__NODE_NAME__-nebula-local-pv-dir
  namespace: clusterpedia-system
  labels:
    app: clusterpedia-internalstorage
    internalstorage.clusterpedia.io/type: nebula
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: clusterpedia-internalstorage
        internalstorage.clusterpedia.io/type: nebula
        job: check-node-local-pv-dir
    spec:
      restartPolicy: Never
      nodeName: __NODE_NAME__
      containers:
      - name: check-dir
        image: nebula:12
        command: ['sh', '-c', 'stat /var/lib/nebulaql/data']
        volumeMounts:
        - name: pv-dir
          mountPath: /var/lib/nebulaql/data
      volumes:
      - name: pv-dir
        hostPath:
          path: /var/local/clusterpedia/internalstorage/nebula
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
